# Generated by Django 4.2.3 on 2023-07-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_image_categorie_image_tags_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=250, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
